### PR TITLE
codeception EA06ContentsManagementCest

### PR DESCRIPTION
**Pull request by hoand-vn**
## 概要(Overview・Refs Issue)
+ PullRequestの目的 : EA06ContentsManagementCest
 
## Discussion
+ contentsmanagement_ページ管理 function NG
  - Reason : in core EC-CUBE TwigInitializeListener: setFrontVaribales() maybe add 
```
/** @var \Symfony\Component\HttpFoundation\ParameterBag $reqAttributes */
        $reqAttributes = $event->getRequest()->attributes;
        $route = $reqAttributes->get('_route');
        if ($route == 'user_data') {
            $routeParams = $reqAttributes->get('_route_params', []);
            $route = isset($routeParams['route']) ? $routeParams['route'] : $reqAttributes->get('route', '');
        }
```

## テスト（Test)
+ CodeCeption local

### CODE REVIEW

**Comment by ryo-endo** [comment]
EA06ContentsManagementCest still NG.
ref https://travis-ci.org/EC-CUBE/eccube-codeception/jobs/337462599

**Comment by ryo-endo** [comment]
@hoand-vn 
about Discussion comment:
Please, create Pull-request to ec-cube/EC-CUBE.
(and rename $reqAttributes → $attributes)

**Comment by hoand-vn** [comment]
@ryo-endo san,
as your feedback , we have PR : https://github.com/EC-CUBE/ec-cube/pull/2822

**Comment by ryo-endo** [comment]
EC-CUBE/ec-cube#2822 の取り込み待ち。

**Pull request merged**
